# Generated by Django 2.1.3 on 2018-12-17 03:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eproperty', '0002_auto_20181216_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=50)),
                ('lastName', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('userName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(through='eproperty.UserRole', to='eproperty.User'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.User'),
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='password', serialize=False, to='eproperty.User')),
                ('encryptedPassword', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=100)),
                ('userAccountExpiryDate', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('passwordMustChanged', models.DateTimeField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
